# global default
container:
  image: continuumio/conda-ci-linux-64-python3.7

makeenv_37_task:
  environment_cache:
    folder: shared
    fingerprint_script: echo $CIRRUS_BUILD_ID
    populate_script:
      - conda create -yq --prefix  $PWD/shared/phys2bids_py37 python=3.7
      - source activate $PWD/shared/phys2bids_py37
      - pip install -e ".[test,doc]"
      - mkdir /tmp/cirrus-ci-build/shared/coverage


unittest_37_task:
  depends_on:
  - makeenv_37
  environment_cache:
    folder: shared
    fingerprint_script: echo $CIRRUS_BUILD_ID
    populate_script:
      - source activate $PWD/shared/phys2bids_py37
  Running_unit_tests_script:
    - source activate $PWD/shared/phys2bids_py37
    - sudo apt-get install -y make
    - make unittest
    - mv /tmp/cirrus-ci-build/.coverage /tmp/cirrus-ci-build/shared/coverage/.coverage.py37


integration_test_37_task:
  depends_on:
  - makeenv_37
  environment_cache:
    folder: shared
    fingerprint_script: echo $CIRRUS_BUILD_ID
    populate_script:
      - source activate $PWD/shared/phys2bids_py37
  Running_integration_tests_script:
  - source activate $PWD/shared/phys2bids_py37
  - sudo apt-get install -y make
  - make integration
  - mv /tmp/cirrus-ci-build/.coverage /tmp/cirrus-ci-build/shared/coverage/.coverage.py37


merge_coverage_37_task:
  depends_on:
  - integration_test_37
  - unittest_37
  environment_cache:
    folder: shared
    fingerprint_script: echo $CIRRUS_BUILD_ID
    populate_script:
      - source activate $PWD/shared/phys2bids_py37
  Running_integration_tests_script:
  - sudo apt-get install -yqq curl
  - source activate $PWD/shared/phys2bids_py37  # depends on makeenv37
  - cd /tmp/src/coverage/
  - coverage combine
  - coverage xml