# global default
container:
  image: continuumio/conda-ci-linux-64-python3.7

unittest_37_task:
  Generate_environment_script:
  - conda create -yq --prefix  $PWD/phys2bids_py37 python=3.7
  - source activate $PWD/phys2bids_py37
  - pip install -e ".[test,doc]"
  Running_unit_tests_script:
    - source activate $PWD/phys2bids_py37
    - sudo apt-get install -y make
    - make unittest
    - mkdir /tmp/cirrus-ci-build/coverage
    - mv /tmp/cirrus-ci-build/.coverage /tmp/cirrus-ci-build/coverage/.coverage.py37
  Coverage_script:
    - apt-get install -yqq curl
    - source activate phys2bids_py37  # depends on makeenv37
    - cd /tmp/cirrus-ci-build/coverage/
    - coverage combine
    - coverage xml