# global default
container:
  image: continuumio/conda-ci-linux-64-python3.7

makeenv_37_task:
  environment_cache:
    folder: shared
    fingerprint_script: echo $CIRRUS_BUILD_ID
    reupload_on_changes: true
    populate_script:
      - conda create -yq --prefix  $PWD/shared/phys2bids_py37 python=3.7
      - source activate $PWD/shared/phys2bids_py37
      - pip install -e ".[test,doc]"
      - mkdir /tmp/cirrus-ci-build/shared/coverage

makeenv_36_task:
  environment_cache:
    folder: shared36
    fingerprint_script: echo ${CIRRUS_BUILD_ID}36
    reupload_on_changes: true
    populate_script:
      - conda create -yq --prefix  $PWD/shared36/phys2bids_py36 python=3.6
      - source activate $PWD/shared36/phys2bids_py36
      - pip install -e ".[test,doc]"
      - mkdir /tmp/cirrus-ci-build/shared36/coverage

makeenv_39_windows_task:
  windows_container:
    image: cirrusci/windowsservercore:2019
  env:
    CIRRUS_SHELL: powershell
  environment_cache:
    folder: shared39
    fingerprint_script: echo $CIRRUS_OS36
    reupload_on_changes: true
    populate_script:
      - choco install make python -y --no-progress; $env:Path += ";c:\python39"; $env:Path += ";c:\python39\Scripts"; refreshenv; echo $env:path
      - pip install --upgrade certifi
      - pip install wheel
      - pip install -e ".[test,doc]"
      - make integration

Unittest_37_task:
  depends_on:
  - makeenv_37
  environment_cache:
    folder: shared
    fingerprint_script: echo $CIRRUS_BUILD_ID
    populate_script:
      - source activate $PWD/shared/phys2bids_py37
    reupload_on_changes: true
  Running_unit_tests_script:
    - sudo apt-get install -y make tree
    - source activate $PWD/shared/phys2bids_py37
    - make unittest
    - mv $PWD/.coverage /tmp/cirrus-ci-build/shared/coverage/.coverage.unittest_37
    - tree /tmp/cirrus-ci-build/shared/coverage

Unittest_36_task:
  depends_on:
  - makeenv_36
  environment_cache:
    folder: shared36
    fingerprint_script: echo ${CIRRUS_BUILD_ID}36
    populate_script:
      - source activate $PWD/shared36/phys2bids_py36
    reupload_on_changes: true
  Running_unit_tests_script:
    - sudo apt-get install -y make tree
    - source activate $PWD/shared36/phys2bids_py36
    - make unittest
    - mv $PWD/.coverage /tmp/cirrus-ci-build/shared36/coverage/.coverage.unittest_36
    - tree /tmp/cirrus-ci-build/shared36/coverage



Integration_test_37_task:
  depends_on:
  - makeenv_37
  environment_cache:
    folder: shared
    fingerprint_script: echo $CIRRUS_BUILD_ID
    populate_script:
      - source activate $PWD/shared/phys2bids_py37
    reupload_on_changes: true
  Running_integration_tests_script:
  - sudo apt-get install -y make tree
  - source activate $PWD/shared/phys2bids_py37
  - make integration
  - mv $PWD/.coverage /tmp/cirrus-ci-build/shared/coverage/.coverage.integration_37
  - tree /tmp/cirrus-ci-build/shared/coverage


Integration_test_36_task:
  depends_on:
  - makeenv_36
  environment_cache:
    folder: shared
    fingerprint_script: echo ${CIRRUS_BUILD_ID}36
    populate_script:
      - source activate $PWD/shared/phys2bids_py36
    reupload_on_changes: true
  Running_integration_tests_script:
  - sudo apt-get install -y make tree
  - source activate $PWD/shared/phys2bids_py36
  - PATH=/home/test_user/.local/bin:$PATH
  - make integration
  - mv $PWD/.coverage /tmp/cirrus-ci-build/shared/coverage/.coverage.integration_36
  - tree /tmp/cirrus-ci-build/shared/coverage

Merge_coverage_37_task:
  depends_on:
  - Integration_test_37
  - Unittest_37
  environment_cache:
    folder: shared
    fingerprint_script: echo $CIRRUS_BUILD_ID
    populate_script:
      - source activate $PWD/shared/phys2bids_py37
  Coverage_script:
  - sudo apt-get install -y tree
  - source activate $PWD/shared/phys2bids_py37  # depends on makeenv37
  - tree /tmp/cirrus-ci-build/shared/coverage
  - cd /tmp/cirrus-ci-build/shared/coverage && coverage combine && coverage xml

Style_check_task:
  depends_on:
  - makeenv_37
  environment_cache:
    folder: shared
    fingerprint_script: echo $CIRRUS_BUILD_ID
    populate_script:
      - source activate $PWD/shared/phys2bids_py37
  Lintin_script:
  - sudo apt-get install -y make
  - source activate $PWD/shared/phys2bids_py37  # depends on makeenv37
  - make lint

Build_docs_task:
  depends_on:
  - makeenv_37
  environment_cache:
    folder: shared
    fingerprint_script: echo $CIRRUS_BUILD_ID
    populate_script:
      - source activate $PWD/shared/phys2bids_py37
  Build_documentation_script:
  - source activate $PWD/shared/phys2bids_py37  # depends on makeenv37
  - make -C docs html

Bids_validate_task:
  depends_on:
  - makeenv_37
  environment_cache:
    folder: shared
    fingerprint_script: echo $CIRRUS_BUILD_ID
    populate_script:
      - source activate $PWD/shared/phys2bids_py37
  Generate_enviroment_script:
  - sudo apt-get install -yqq wget curl tree
  - sudo curl -sL https://deb.nodesource.com/setup_15.x | sudo bash -
  - sudo apt-get install -yqq nodejs
  - sudo npm install -g bids-validator
  Dowload data and execute pipeline_script:
  - wget -O Test1_multifreq_onescan.txt https://osf.io/7se4t/download
  - wget -O heur_test_multifreq.py https://osf.io/ehx6j/download
  - source activate $PWD/shared/phys2bids_py37
  - PATH=/home/test_user/.local/bin:$PATH
  - pip install -e ".[test,doc]" && phys2bids -in Test1_multifreq_onescan.txt -chtrig 1 -ntp 30 -tr 1.2 -outdir physio_bids -heur heur_test_multifreq.py -sub 006 -ses 01
  Run validator_script:
    - wget -O sub-006_ses-01_task-test_rec-biopac_run-01_bold.json https://osf.io/6j8f7/download
    - wget -O sub-006_ses-01_task-test_rec-biopac_run-01_bold.nii.gz https://osf.io/wus2p/download
    - mv sub-006_ses-01_task-test_rec-biopac_run-01_bold* physio_bids/sub-006/ses-01/func
    - tree physio_bids
    - bids-validator  physio_bids


