# global default
container:
  image: continuumio/conda-ci-linux-64-python3.7
  cpu: 1

makeenv_task:
  env:
    matrix:
      PYTHON: 3.6
      PYTHON: 3.7
      PYTHON: 3.8
      PYTHON: 3.9
  environment_cache:
    folder: conda-env
    fingerprint_script: 
      - echo $PYTHON
      - cat setup.py
    populate_script:
      - conda create -yq --prefix  $PWD/conda-env python=$PYTHON
      - source activate $PWD/conda-env
      - pip install -e '.[test,doc]'
  activate_script: source activate $PWD/conda-env

Unittest_task:
  depends_on: 
    - makeenv
  env:
    matrix:
      PYTHON: 3.6
      PYTHON: 3.7
      PYTHON: 3.8
      PYTHON: 3.9
  environment_cache:
    folder: conda-env
    fingerprint_script: 
      - echo $PYTHON
      - cat setup.py
    populate_script:
      - source activate $PWD/conda-env
  Running_unit_tests_script:
    - sudo apt-get install -y make tree
    - source activate $PWD/conda-env
    - make unittest
    - mv /tmp/cirrus-ci-build/coverage_unit.xml /tmp/cirrus-ci-build/coverage_unit_$PYTHON.xml

Integration_task:
  depends_on: 
    - makeenv
  env:
    matrix:
      PYTHON: 3.6
      PYTHON: 3.7
      PYTHON: 3.8
      PYTHON: 3.9
  environment_cache:
    folder: conda-env
    fingerprint_script: 
      - echo $PYTHON
      - cat setup.py
    populate_script:
      - source activate $PWD/conda-env
  Running_unit_tests_script:
    - sudo apt-get install -y make
    - source activate $PWD/conda-env
    - PATH=/home/test_user/.local/bin:$PATH
    - make integration
    - mv /tmp/cirrus-ci-build/coverage_integration.xml /tmp/cirrus-ci-build/coverage_integration_$PYTHON.xml

# makeenv_39_task:
#   environment_cache:
#     folder: shared39
#     fingerprint_script: echo ${CIRRUS_BUILD_ID}39
#     reupload_on_changes: true
#     populate_script:
#       - conda create -yq --prefix  $PWD/shared39/phys2bids_py39 python=3.9
#       - source activate $PWD/shared39/phys2bids_py39
#       - pip install -e '.[test,doc]'
#       - mkdir /tmp/cirrus-ci-build/shared39/coverage

# makeenv_38_task:
#   environment_cache:
#     folder: shared38
#     fingerprint_script: echo ${CIRRUS_BUILD_ID}38
#     reupload_on_changes: true
#     populate_script:
#       - conda create -yq --prefix  $PWD/shared38/phys2bids_py38 python=3.8
#       - source activate $PWD/shared38/phys2bids_py38
#       - pip install -e '.[test,doc]'
#       - mkdir /tmp/cirrus-ci-build/shared38/coverage

# makeenv_37_task:
#   environment_cache:
#     folder: shared
#     fingerprint_script: echo $CIRRUS_BUILD_ID
#     reupload_on_changes: true
#     populate_script:
#       - conda create -yq --prefix  $PWD/shared/phys2bids_py37 python=3.7
#       - source activate $PWD/shared/phys2bids_py37
#       - pip install -e '.[test,doc]'
#       - mkdir /tmp/cirrus-ci-build/shared/coverage

# makeenv_36_task:
#   environment_cache:
#     folder: shared36
#     fingerprint_script: echo ${CIRRUS_BUILD_ID}36
#     reupload_on_changes: true
#     populate_script:
#       - conda create -yq --prefix  $PWD/shared36/phys2bids_py36 python=3.6
#       - source activate $PWD/shared36/phys2bids_py36
#       - pip install -e '.[test,doc]'
#       - mkdir /tmp/cirrus-ci-build/shared36/coverage

# Unittest_39_task:
#   depends_on:
#   - makeenv_39
#   environment_cache:
#     folder: shared39
#     fingerprint_script: echo ${CIRRUS_BUILD_ID}39
#     populate_script:
#       - source activate $PWD/shared39/phys2bids_py39
#     reupload_on_changes: true
#   Running_unit_tests_script:
#     - sudo apt-get install -y make tree
#     - source activate $PWD/shared39/phys2bids_py39
#     - make unittest
#     - mv $PWD/.coverage /tmp/cirrus-ci-build/shared39/coverage/.coverage.unittest_39
#     - tree /tmp/cirrus-ci-build/shared39/coverage

# Unittest_38_task:
#   depends_on:
#   - makeenv_38
#   environment_cache:
#     folder: shared38
#     fingerprint_script: echo ${CIRRUS_BUILD_ID}38
#     populate_script:
#       - source activate $PWD/shared38/phys2bids_py38
#     reupload_on_changes: true
#   Running_unit_tests_script:
#     - sudo apt-get install -y make tree
#     - source activate $PWD/shared38/phys2bids_py38
#     - make unittest
#     - mv $PWD/.coverage /tmp/cirrus-ci-build/shared38/coverage/.coverage.unittest_38
#     - tree /tmp/cirrus-ci-build/shared38/coverage

# Unittest_37_task:
#   depends_on:
#   - makeenv_37
#   environment_cache:
#     folder: shared
#     fingerprint_script: echo $CIRRUS_BUILD_ID
#     populate_script:
#       - source activate $PWD/shared/phys2bids_py37
#     reupload_on_changes: true
#   Running_unit_tests_script:
#     - sudo apt-get install -y make tree
#     - source activate $PWD/shared/phys2bids_py37
#     - make unittest
#     - mv $PWD/.coverage /tmp/cirrus-ci-build/shared/coverage/.coverage.unittest_37
#     - tree /tmp/cirrus-ci-build/shared/coverage

# Unittest_36_task:
#   depends_on:
#   - makeenv_36
#   environment_cache:
#     folder: shared36
#     fingerprint_script: echo ${CIRRUS_BUILD_ID}36
#     populate_script:
#       - source activate $PWD/shared36/phys2bids_py36
#     reupload_on_changes: true
#   Running_unit_tests_script:
#     - sudo apt-get install -y make tree
#     - source activate $PWD/shared36/phys2bids_py36
#     - make unittest
#     - mv $PWD/.coverage /tmp/cirrus-ci-build/shared36/coverage/.coverage.unittest_36
#     - tree /tmp/cirrus-ci-build/shared36/coverage

# Integration_test_39_task:
#   depends_on:
#   - makeenv_39
#   environment_cache:
#     folder: shared39
#     fingerprint_script: echo ${CIRRUS_BUILD_ID}39
#     populate_script:
#       - source activate $PWD/shared39/phys2bids_py39
#     reupload_on_changes: true
#   Running_integration_tests_script:
#   - sudo apt-get install -y make tree
#   - source activate $PWD/shared39/phys2bids_py39
#   - PATH=/home/test_user/.local/bin:$PATH
#   - make integration
#   - mv $PWD/.coverage /tmp/cirrus-ci-build/shared39/coverage/.coverage.integration_39
#   - tree /tmp/cirrus-ci-build/shared39/coverage

# Integration_test_38_task:
#   depends_on:
#   - makeenv_38
#   environment_cache:
#     folder: shared38
#     fingerprint_script: echo ${CIRRUS_BUILD_ID}38
#     populate_script:
#       - source activate $PWD/shared38/phys2bids_py38
#     reupload_on_changes: true
#   Running_integration_tests_script:
#   - sudo apt-get install -y make tree
#   - source activate $PWD/shared38/phys2bids_py38
#   - PATH=/home/test_user/.local/bin:$PATH
#   - make integration
#   - mv $PWD/.coverage /tmp/cirrus-ci-build/shared38/coverage/.coverage.integration_38
#   - tree /tmp/cirrus-ci-build/shared38/coverage

# Integration_test_37_task:
#   depends_on:
#   - makeenv_37
#   environment_cache:
#     folder: shared
#     fingerprint_script: echo $CIRRUS_BUILD_ID
#     populate_script:
#       - source activate $PWD/shared/phys2bids_py37
#     reupload_on_changes: true
#   Running_integration_tests_script:
#   - sudo apt-get install -y make tree tar
#   - source activate $PWD/shared/phys2bids_py37
#   - make integration
#   - mv /tmp/cirrus-ci-build/coverage.xml /tmp/cirrus-ci-build/coverage_integration_37.xml
#   coverage_integration_37_artifacts:
#     path: "coverage_integration_37.xml"

# download_artifact_task:
#   depends_on:
#   - Integration_test_37
#   download_script:
#   - sudo apt-get install -y tree wget tar
#   - wget https://api.cirrus-ci.com/v1/artifact/build/${CIRRUS_BUILD_ID}//tmp/cirrus-ci-build/coverage_integration_37.xml
#   - tree .

# Integration_test_36_task:
#   depends_on:
#   - makeenv_36
#   environment_cache:
#     folder: shared36
#     fingerprint_script: echo ${CIRRUS_BUILD_ID}36
#     populate_script:
#       - source activate $PWD/shared36/phys2bids_py36
#     reupload_on_changes: true
#   Running_integration_tests_script:
#   - sudo apt-get install -y make tree
#   - source activate $PWD/shared36/phys2bids_py36
#   - PATH=/home/test_user/.local/bin:$PATH
#   - make integration
#   - mv $PWD/.coverage /tmp/cirrus-ci-build/shared36/coverage/.coverage.integration_36
#   - tree /tmp/cirrus-ci-build/shared36/coverage

# Merge_coverage_37_task:
#   depends_on:
#   - Integration_test_37
#   - Unittest_37
#   environment_cache:
#     folder: shared
#     fingerprint_script: echo $CIRRUS_BUILD_ID
#     populate_script:
#       - source activate $PWD/shared/phys2bids_py37
#   Coverage_script:
#   - sudo apt-get install -y tree
#   - source activate $PWD/shared/phys2bids_py37  # depends on makeenv37
#   - tree /tmp/cirrus-ci-build/shared/coverage
#   - cd /tmp/cirrus-ci-build/shared/coverage && coverage combine && coverage xml

# Style_check_task:
#   depends_on:
#   - makeenv_37
#   environment_cache:
#     folder: shared
#     fingerprint_script: echo $CIRRUS_BUILD_ID
#     populate_script:
#       - source activate $PWD/shared/phys2bids_py37
#   Lintin_script:
#   - sudo apt-get install -y make
#   - source activate $PWD/shared/phys2bids_py37  # depends on makeenv37
#   - make lint

# Build_docs_task:
#   depends_on:
#   - makeenv_37
#   environment_cache:
#     folder: shared
#     fingerprint_script: echo $CIRRUS_BUILD_ID
#     populate_script:
#       - source activate $PWD/shared/phys2bids_py37
#   Build_documentation_script:
#   - source activate $PWD/shared/phys2bids_py37  # depends on makeenv37
#   - make -C docs html

# Bids_validate_task:
#   depends_on:
#   - makeenv_37
#   environment_cache:
#     folder: shared
#     fingerprint_script: echo $CIRRUS_BUILD_ID
#     populate_script:
#       - source activate $PWD/shared/phys2bids_py37
#   Generate_enviroment_script:
#   - sudo apt-get install -yqq wget curl tree
#   - sudo curl -sL https://deb.nodesource.com/setup_15.x | sudo bash -
#   - sudo apt-get install -yqq nodejs
#   - sudo npm install -g bids-validator
#   Dowload data and execute pipeline_script:
#   - wget -O Test1_multifreq_onescan.txt https://osf.io/7se4t/download
#   - wget -O heur_test_multifreq.py https://osf.io/ehx6j/download
#   - source activate $PWD/shared/phys2bids_py37
#   - PATH=/home/test_user/.local/bin:$PATH
#   - pip install -e '.[test,doc]' && phys2bids -in Test1_multifreq_onescan.txt -chtrig 1 -ntp 30 -tr 1.2 -outdir physio_bids -heur heur_test_multifreq.py -sub 006 -ses 01
#   Run validator_script:
#     - wget -O sub-006_ses-01_task-test_rec-biopac_run-01_bold.json https://osf.io/6j8f7/download
#     - wget -O sub-006_ses-01_task-test_rec-biopac_run-01_bold.nii.gz https://osf.io/wus2p/download
#     - mv sub-006_ses-01_task-test_rec-biopac_run-01_bold* physio_bids/sub-006/ses-01/func
#     - tree physio_bids
#     - bids-validator  physio_bids

# Integration_windows_task:
#   windows_container:
#     matrix:
#       - dockerfile: .ci/w_python_39
#       - dockerfile: .ci/w_python_38
#       - dockerfile: .ci/w_python_37
#     cpu: 1
#   env:
#     CIRRUS_SHELL: powershell
#   environment_cache:
#     folder: shared39
#     fingerprint_script: echo 362
#     reupload_on_changes: true
#     populate_script:
#       - pip install -e '.[test,doc]'
#   Running_integration_script:
#     - choco install make -y --no-progress
#     - make integration

# Unittest_windows_task:
#   windows_container:
#     matrix:
#       - dockerfile: .ci/w_python_39
#       - dockerfile: .ci/w_python_38
#       - dockerfile: .ci/w_python_37
#     cpu: 1
#   env:
#     CIRRUS_SHELL: powershell
#   environment_cache:
#     folder: shared39
#     fingerprint_script: echo 362
#     reupload_on_changes: true
#     populate_script:
#       - pip install -e '.[test,doc]'
#   Running_integration_script:
#     - choco install make -y --no-progress
#     - make unittest

