# global default
container:
  image: continuumio/conda-ci-linux-64-python3.7

makeenv_37_task:
  environment_cache:
    folder: shared
    fingerprint_script: echo $CIRRUS_BUILD_ID
    populate_script:
      - conda create -yq --prefix  $PWD/shared/phys2bids_py37 python=3.7
      - source activate $PWD/shared/phys2bids_py37
      - pip install -e ".[test,doc]"
      - mkdir /tmp/cirrus-ci-build/shared/coverage


unittest_37_task:
  depends_on:
  - makeenv_37
  environment_cache:
    folder: shared
    fingerprint_script: echo $CIRRUS_BUILD_ID
    populate_script:
      - source activate $PWD/shared/phys2bids_py37
  Running_unit_tests_script:
    - source activate $PWD/shared/phys2bids_py37
    - sudo apt-get install -y make tree
    - py.test --skipintegration --cov-append --cov-report=xml:/tmp/cirrus-ci-build/shared/coverage/coverage_unittest_37.xml --cov=phys2bids phys2bids/
    - tree /tmp/cirrus-ci-build/shared/coverage


integration_test_37_task:
  depends_on:
  - makeenv_37
  environment_cache:
    folder: shared
    fingerprint_script: echo $CIRRUS_BUILD_ID
    populate_script:
      - source activate $PWD/shared/phys2bids_py37
  Running_integration_tests_script:
  - source activate $PWD/shared/phys2bids_py37
  - sudo apt-get install -y make tree
  - pytest --log-cli-level=INFO --cov-append --cov-report=xml:/tmp/cirrus-ci-build/shared/coverage/coverage_integration_37.xml --cov=phys2bids -k test_integration phys2bids/tests/test_integration.py
  - tree /tmp/cirrus-ci-build/shared/coverage


merge_coverage_37_task:
  depends_on:
  - integration_test_37
  - unittest_37
  environment_cache:
    folder: shared
    fingerprint_script: echo $CIRRUS_BUILD_ID
    populate_script:
      - source activate $PWD/shared/phys2bids_py37
  Coverage_script:
  - sudo apt-get install -yqq curl
  - source activate $PWD/shared/phys2bids_py37  # depends on makeenv37
  - cd $PWD/shared/coverage/
  - coverage xml