# global default
container:
  image: continuumio/miniconda3
env:
  CIRRUS_WORKING_DIR: /usr/local/bin

task:
  name: makeenv_37
  env_install_script:
    - git clone --branch=$CIRRUS_BRANCH
    - pip install -e ".[test,doc]"