# global default
container:
  image: continuumio/miniconda3

task:
  name: makeenv_37
    folder: /tmp/src/phys2bids
    env_install_script:
      - git clone --branch=$CIRRUS_BRANCH
      - pip install -e ".[test,doc]"