# Python CircleCI 2.1 configuration file
#
#
#
version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5
  win: circleci/windows@2.2.0
jobs:

  makeenv_37:
    docker:
      - image: continuumio/miniconda3
    working_directory: /tmp/src/phys2bids
    steps:
      - checkout
      - persist_to_workspace:
          root: /tmp
          paths:
              - src/phys2bids
      - restore_cache:
          key: conda-py37-v1-{{ checksum "setup.cfg" }}
      - run:
          name: Generate environment
          command: |
            if [[ -e /opt/conda/envs/phys2bids_py37 ]]; then
              echo "Restoring environment from cache"
                source activate phys2bids_py37
            else
              conda create -yq -n phys2bids_py37 python=3.7
              source activate phys2bids_py37
              pip install -e ".[test,doc]"
            fi
      - save_cache:
          key: conda-py37-v1-{{ checksum "setup.cfg" }}
          paths:
              - /opt/conda/envs/phys2bids_py37
